npm install \
  @supabase/supabase-js \
  jsonwebtoken \
  next-cookies \
  stripe \
  @stripe/stripe-js \
  @stripe/react-stripe-js \
  stripe-webhook-middleware \
  @tanstack/react-query \
  @supabase/postgrest-js \
  geofirestore \
  react-ga4 \
  mixpanel-browser \
  @sentry/nextjs \
  react-leaflet \
  leaflet \
  react-map-gl \
  react-hook-form \
  yup \
  @hookform/resolvers \
  date-fns \
  zustand \
  redux \
  react-redux \
  @headlessui/react \
  @radix-ui/react-* \
  react-select \
  geolib \
  currency.js \
  number-precision \
  dotenv \
  next-i18next \
  next-seo \
  next-pwa \
  react-dropzone \
  @supabase/storage-js \
  sharp \
  eslint \
  eslint-config-next \
  prettier \
  jest \
  @testing-library/react \
  @testing-library/jest-dom \
  eslint-plugin-jsx-a11y --save-dev